export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const SET_EMPLOYEE = "SET_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SET_ROULES = "SET_ROULES";